site_name: Bixal Techbook
repo_url: https://github.com/Bixal/handbook/
site_url: https://techbook.bixal.com/en/latest/
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
plugins:
    - search
extra_css:
    - css/extra.css
